repos:
  - repo: __LIVE_TEST_ORG__/it-settings-a
  - repo: __LIVE_TEST_ORG__/it-merge-commit-a
  - repo: __LIVE_TEST_ORG__/it-rebase-merge-a
  - repo: __LIVE_TEST_ORG__/it-update-branch-a
  - repo: __LIVE_TEST_ORG__/it-immutable-releases-a
  - repo: __LIVE_TEST_ORG__/it-code-scanning-a
  - repo: __LIVE_TEST_ORG__/it-secret-scanning-a
  - repo: __LIVE_TEST_ORG__/it-push-protection-a
  - repo: __LIVE_TEST_ORG__/it-dependabot-alerts-a
  - repo: __LIVE_TEST_ORG__/it-dependabot-security-updates-a
  - repo: __LIVE_TEST_ORG__/it-dependabot-yml-a
  - repo: __LIVE_TEST_ORG__/it-gitignore-a
  - repo: __LIVE_TEST_ORG__/it-rulesets-a
  - repo: __LIVE_TEST_ORG__/it-rulesets-update-a
  - repo: __LIVE_TEST_ORG__/it-pull-request-template-a
  - repo: __LIVE_TEST_ORG__/it-workflow-single-a
  - repo: __LIVE_TEST_ORG__/it-workflows-a
  - repo: __LIVE_TEST_ORG__/it-autolinks-a
  - repo: __LIVE_TEST_ORG__/it-copilot-a
  - repo: __LIVE_TEST_ORG__/it-package-json-a
  - repo: __LIVE_TEST_ORG__/it-package-json-scripts-a
  - repo: __LIVE_TEST_ORG__/it-package-json-engines-a
  - repo: __LIVE_TEST_ORG__/it-codeowners-root-a
  - repo: __LIVE_TEST_ORG__/it-codeowners-docs-a
  - repo: __LIVE_TEST_ORG__/it-codeowners-vars-a
  - repo: __LIVE_TEST_ORG__/it-pr-up-to-date-a
  - repo: __LIVE_TEST_ORG__/it-pr-updated-a
  - repo: __LIVE_TEST_ORG__/it-pr-dry-run-update-a
  - repo: __LIVE_TEST_ORG__/it-pr-workflows-created-a
  - repo: __LIVE_TEST_ORG__/it-pr-workflows-mixed-a
  - repo: __LIVE_TEST_ORG__/it-pr-package-json-up-to-date-a
  - repo: __LIVE_TEST_ORG__/it-pr-package-json-updated-a
  - repo: __LIVE_TEST_ORG__/it-pr-package-json-dry-run-update-a
  - repo: __LIVE_TEST_ORG__/it-topics-a
  - repo: __LIVE_TEST_ORG__/it-codeowners-a
  - repo: __LIVE_TEST_ORG__/it-warning-a
  - repo: __LIVE_TEST_ORG__/it-unchanged-a
  - repo: __LIVE_TEST_ORG__/it-dry-run-a
